
user www-data;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;

    proxy_cache_path /data/cache_osm levels=1:2 keys_zone=osm:10m max_size=20g
                     inactive=30d use_temp_path=off;

    upstream openstreetmap {
      server tile.openstreetmap.org:443;
      server a.tile.openstreetmap.org:443;
      server b.tile.openstreetmap.org:443;
      server c.tile.openstreetmap.org:443;

      server tile.osm.org:443;
      server a.tile.osm.org:443;
      server b.tile.osm.org:443;
      server c.tile.osm.org:443;
    }

    server {
      listen 80 default_server;

      proxy_cache_background_update on;
      proxy_cache_lock on;
      proxy_cache osm;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504 http_403 http_404 http_429;
      proxy_cache_valid 200 302 30d;
      proxy_cache_valid 301 1h;
      proxy_cache_valid any 1m;
      proxy_connect_timeout 10s;
      proxy_hide_header Set-Cookie;
      proxy_hide_header Strict-Transport-Security;
      proxy_hide_header Expect-Ct;
      proxy_hide_header Via;
      proxy_hide_header Referer;
      proxy_hide_header X-Blocked;
      proxy_hide_header Cookie;
      proxy_hide_header X-Served-By;
      proxy_hide_header Origin;
      proxy_hide_header X-Cache;
      proxy_hide_header X-Cache-Lookup;
      proxy_ignore_headers Cache-Control Set-Cookie;

  proxy_set_header Referer "";
  proxy_set_header Origin "";
  proxy_set_header Forwarded "";
  proxy_set_header X-Forwarded-For "";
  proxy_set_header X-Forwarded-Host "";
  proxy_set_header X-Forwarded-Proto "";
  proxy_set_header X-Forwarded-Port "";
  proxy_set_header X-Real-IP "";
  proxy_set_header Via "";
  proxy_set_header Cookie "";

      proxy_next_upstream error timeout http_500 http_502 http_503 http_504 http_403 http_404 http_429;
      proxy_next_upstream_timeout 0;
      proxy_next_upstream_tries 0;

      expires 30d;
      add_header X-Cache-Status $upstream_cache_status;

      location ~ ^/street {
        rewrite ^/street(.*)$ $1 break;
        proxy_pass https://openstreetmap;
        proxy_ssl_server_name on;
        proxy_ssl_name tile.openstreetmap.org;
        proxy_set_header Host tile.openstreetmap.org;

      }
    }
}
